### ISSUE TITLE
MultiQML creates python error, won't open

### ISSUE THREAD

**Issue by ebeers2** [nextgis/qgis_multiqml#11]
I installed this plugin a few months ago, it worked brilliantly.  Then it stopped working.  Clicking on the tool at first generated a Python error message, now clicking does...nothing.  I tried reinstalling the plugin, still nothing.  I minimized all my windows to see if a dialog was hidden, no luck.  I am using QGIS 2.1.8/Windows 10.

**Comment by ivanbarsukov** [comment]
QGIS 2 is no longer supported
